AWSTemplateFormatVersion: "2010-09-09"

Description: LogGroup Create

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Name Prefix
        Parameters:
          - PJPrefix
      - Label:
          default: CloudWatch Configuration
        Parameters:
          - LogGroupName
          - RetentionInDays


Parameters:
  #=================================
  # Prefixを指定
  #=================================
  PJPrefix:
    Type: String

  #=================================
  # CloudWatch関連
  #=================================
  LogGroupName:
    Type: String
    Default: clientvpn

  RetentionInDays:
    Type: String
    Default: 1
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365

  LogStreamName:
    Type: String
    Default: connection-log

#=================================
# Resources
#=================================
Resources:

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Ref LogGroupName
      RetentionInDays: !Ref RetentionInDays
      Tags: 
        - Key: Name
          Value: !Sub ${PJPrefix}-Log-Group

  LogStream:
    Type: AWS::Logs::LogStream
    Properties: 
      LogGroupName: !Ref LogGroup
      LogStreamName: !Ref LogStreamName

#=================================
# output
#=================================
Outputs:

  LogGroup:
    Value: !Ref LogGroup
    Export:
      Name: LogGroupName

  LogStream:
    Value: !Ref LogStream
    Export:
      Name: LogStreamName